Fix build by updating dependencies & fix panic on receiving `mimeapps.list` with lines with no handlers. (#37)
* Update Cargo.lock

Fixes `cargo build` failure from dep `proc-macro2` not exposing methods
`before()` and `after()` needed for feature `proc_macro_span_shrink`.

```
error[E0635]: unknown feature `proc_macro_span_shrink`
  --> /home/sam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.52/src/lib.rs:92:30
   |
92 |     feature(proc_macro_span, proc_macro_span_shrink)
   |                              ^^^^^^^^^^^^^^^^^^^^^^
```

* Handle `mimeapps.list` line with no handlers.

Avoid unwrapping a potentially missing handler.

Fixes panic described in #38.